### ISSUE TITLE
Another libGL error: No matching fbConfigs or visuals found

### ISSUE THREAD

**Issue by zhaozhongch** [SoonminHwang/dockers#2]
I know this problem has been mentioned in #1. But in my case, it may be different.
My Nvidia driver is 430, my GPU is GTX1050 and I use Nvidia docker1.
In problem #1 it suggests connecting the driver with docker. However, I don't have `nvidia-430` folder  in `/usr/lib` but I have it in `/usr/lib/x86_64-linux-gnu`. I don't have anything about nvidia in `/usr/lib32` ... So I cannot implement the solution from #1
My docker run command is 
```
docker run \
     --name ubuntu16_cuda8_con \
     --user=root \
     --gpu all \
     --rm \
     --detach=false \
     -e DISPLAY=${DISPLAY} \
     -v /tmp/.X11-unix:/tmp/.X11-unix \
     -v `pwd`:/mnt/shared \
     -it \
     ubuntu16_cuda8_img /bin/bash -c "cd /mnt/shared && cd Pangolin/build/examples/HelloPangolin && ./HelloPangolin"
```
I just try to run the simple `HelloPangolin` example to test. And get the following error
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options
```

**Comment by minna-ust** [comment]
have the same problem

**Comment by zhaozhongch** [comment]
I fix this by pull the docker [cudagl](https://hub.docker.com/r/nvidia/cudagl) image
